name: normalise_emission_factors
version: 1.0.0
config-version: 2
profile: transform

model-paths: [models]
macro-paths: [macros]
seed-paths: [seeds]
test-paths: [tests]
analysis-paths: [analyses]
snapshot-paths: [snapshots]

clean-targets:
  - target
  - dbt_packages

models:
  normalise_emission_factors:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table